spring:
  application:
    name: tms

  jackson:
    time-zone: Asia/Seoul


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    RDS
#    url: jdbc:mysql://tmsdb.clgq6ysgupxk.ap-northeast-2.rds.amazonaws.com:3306/TMSDB?serverTimezone=UTC
#    username: kscold
#    password: tmdcks6502

#    박혜정 local
#    url: jdbc:mysql://localhost:3306/tms?serverTimezone=UTC
#    username: root
#    password: 3516


#    김승찬 local
    url: jdbc:mysql://localhost:3306/TMSDB?serverTimezone=UTC
    username: root
    password: Tmdcks6502@


  #  jpa:
  #    properties:
  #      hibernate:
  #        show_sql: true
  #        format_sql: true
  #        use_sql_comments: true
  #    hibernate:
  #      ddl-auto: create
  #    database-platform: org.hibernate.dialect.MySQLDialect
  #    show-sql: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      ddl-auto: create
#      ddl-auto: none
      naming:
        # 네이밍할때 _ 안붙이고 카멜케이스로 만들어주는 속성
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: chan6502
    password: yywaqxhzevunyckq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#logging.level:
#  org.hibernate.SQL: debug

logging:
  level:
    #    root: INFO
    web.login: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace


server:
  servlet:
    session:
      timeout: 1800