#spring:
#  application:
#    name: tms
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
##    url: jdbc:mysql://localhost:3306/tms?serverTimezone=UTC
##    username: root
##    password: 3516
#    url: jdbc:mysql://ec2-3-39-185-190.ap-northeast-2.compute.amazonaws.com:3306/TMSDB
#    username: kscold
#    password: Tmdcks6502@
#
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.MySQLDialect
#    show-sql: true
#
##logging.level:
##  org.hibernate.SQL: debug
#
#logging:
#  level:
##    root: INFO
#    web.login: DEBUG
#    org.hibernate.SQL: DEBUG
#
#server:
#  servlet:
#    session:
#      timeout: 1800

spring:
  application:
    name: tms

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
      #    url: jdbc:mysql://localhost:3306/tms?serverTimezone=UTC
      #    url: jdbc:mysql://ec2-3-39-185-190.ap-northeast-2.compute.amazonaws.com:3306/TMSDB
      #    username: kscold
    #    password: Tmdcks6502@
    url: jdbc:mysql://localhost:3306/TMSDB?serverTimezone=UTC
    username: root
    password: Tmdcks6502@

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.orm.jdbc.bind: trace

